Add env SKIP_INJECT for permit task for clean repo

diff --git a/sark-localcreaterepo b/sark-localcreaterepo
--- a/sark-localcreaterepo
+++ b/sark-localcreaterepo
@@ -5,6 +5,7 @@ export LC_ALL=en_US.UTF-8
 export SKIP_PULL="${SKIP_PULL:-0}"
 export SKIP_PUSH="${SKIP_PUSH:-0}"
 export SKIP_COMMIT="${SKIP_COMMIT:-0}"
+export SKIP_INJECT="${SKIP_INJECT:-0}"
 export SAB_WORKSPACE="${SAB_WORKSPACE:-$PWD}"
 
 # Add additional option for eit inject command.
@@ -114,10 +115,12 @@ if  [ -n "${TOREMOVE_BEFORE}" ] ; then
   echo "=== Removing packages before inject COMPLETED ==="
 fi
 
-echo "=== Injecting packages ==="
-echo "INJECT = ${built_pkgs}"
-eit inject ${EIT_INJECT_OPTS} --to ${REPOSITORY_NAME} --quick ${built_pkgs} || { echo "ouch unable to inject" && exit 3; }
-echo "=== Inject COMPLETED ====="
+if [[ ${SKIP_INJECT} = 0 ]] ; then
+  echo "=== Injecting packages ==="
+  echo "INJECT = ${built_pkgs}"
+  eit inject ${EIT_INJECT_OPTS} --to ${REPOSITORY_NAME} --quick ${built_pkgs} || { echo "ouch unable to inject" && exit 3; }
+  echo "=== Inject COMPLETED ====="
+fi
 
 echo "=== Removing packages ==="
 
