Update sark-localbuild

diff --git a/sark-localbuild b/sark-localbuild
--- a/sark-localbuild
+++ b/sark-localbuild
@@ -5,7 +5,7 @@ export GENKEY_PHASE=${GENKEY_PHASE:-false} # Disable for default.
 export VAGRANT_DIR="${VAGRANT_DIR:-$(pwd)}"
 export REPOSITORY_NAME="${REPOSITORY_NAME:-$(basename $(pwd))}"
 export REPOSITORY_NAME="${REPOSITORY_NAME:-default}"
-
+export LC_ALL=en_US.UTF-8
 export DOCKER_OPTS="--cap-add=SYS_PTRACE -t"
 # Speed up test runs by disabling slow syncs and mirror sorts
 export SKIP_PORTAGE_SYNC="${SKIP_PORTAGE_SYNC:-0}"
@@ -20,8 +20,6 @@ if [ ! -e build.yaml ]; then
 fi
 
 load_env_from_yaml build.yaml
-
-equo i entropy-server
 
 export OUTPUT_DIR="${VAGRANT_DIR}/artifacts/${REPOSITORY_NAME}-binhost"
 export CHECK_BUILD_DIFFS=${CHECK_BUILD_DIFFS:-1}
@@ -107,7 +105,7 @@ fi
 [ -f "${VAGRANT_DIR}/confs/${REPOSITORY_NAME}.pub" ] && [ -f "${VAGRANT_DIR}/confs/${REPOSITORY_NAME}.key" ] && { ! eit key status ${REPOSITORY_NAME}; } && \
 eit key import ${REPOSITORY_NAME} ${VAGRANT_DIR}/confs/${REPOSITORY_NAME}.key ${VAGRANT_DIR}/confs/${REPOSITORY_NAME}.pub && { eit key sign ${REPOSITORY_NAME} || true; } && { echo "=== Repository key imported successfully ==="; }
 echo "=== Injecting packages ==="
-echo "Yes" | eit inject ${built_pkgs} || { echo "ouch unable to inject" && exit 3; }
+echo "Yes Yes Yes" | eit inject ${built_pkgs} || { echo "ouch unable to inject" && exit 3; }
 echo "Yes Yes Yes" | eit commit --quick
 echo "=== Pushing built packages locally ==="
 eit push --quick --force
