sark-localinjector: Add installation of repo pkgs with eit pull

diff --git a/sark-localinjector b/sark-localinjector
--- a/sark-localinjector
+++ b/sark-localinjector
@@ -88,6 +88,27 @@ else
   cp -rvf ${FILTER_DIR}/* /usr/portage/packages || true
 fi
 
+# If is execute eit pull then we need install all repo packages to avoid
+# that not installed packages are handled as to remove.
+if [ "$SKIP_PULL" = "0" ] ; then
+  if [ -n "$SAB_STAGING_BUILD_RESOURCES" ] ; then
+    for r in $SAB_STAGING_BUILD_RESOURCES ; do
+      pkgs_checker_sark_list_opts="$pkgs_checker_sark_list_opts -s $r"
+    done
+
+    repo_pkgs=$(${PKGS_CHECKER_BIN} sark pkglist $pkgs_checker_sark_list_opts)
+
+    if [ -n "${repo_pkgs}" ] ; then
+      equo i $repo_pkgs || {
+        echo "Error on install repository packages"
+        exit 1
+      }
+    else
+      echo "No packages of repo ${REPOSITORY_NAME} available."
+    fi
+  fi
+fi
+
 TEMPDIR=$(mktemp -d)
 
 # Checking diffs
