sark-localinjector: Integration pkgs-checker filter

diff --git a/sark-localinjector b/sark-localinjector
--- a/sark-localinjector
+++ b/sark-localinjector
@@ -16,6 +16,9 @@ export SAB_BUILDFILE="${SAB_BUILDFILE:-build.yaml}"
 
 export SAB_STAGING_DIRS="${SAB_STAGING_DIRS:-staging1 staging2}"
 
+# Pkgs-checker filter option
+export PKG_CHECKER_FILTER_OPTS="${PKG_CHECKER_FILTER_OPTS:--v -L INFO -r ${SAB_WORKSPACE}/${SAB_ARTIFACTS_DIR}/ -f ${SAB_BUILDFILE}}"
+
 . /sbin/sark-functions.sh
 
 if [ ! -e "${SAB_BUILDFILE}" ]; then
@@ -101,6 +104,12 @@ else
   # Inject all packages available under /usr/portage/packages
   cp -R /usr/portage/packages/* ${TEMPDIR} || true
 fi
+
+# Filter inject of the files
+${PKGS_CHECKER_BIN} ${PKG_CHECKER_FILTER_OPTS} -d ${TEMPDIR}|| {
+  echo "Error on filter packages"
+  exit 1
+}
 
 export PKGS_CACHE_DIR=$TEMPDIR
 sark-localcreaterepo
